name: LaTeX

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker://xucheng/texlive-full
      with:
        entrypoint: latexmk
        args: -pdf dialogue
    - uses: docker://pandoc/latex
      with:
        args: -s -f latex -t icml -o dialogue.icml --bibliography=dialogue.bib --filter pandoc-citeproc --csl=splncs.csl dialogue.tex
    - uses: actions/upload-artifact@v2
      with:
        name: dialogue
        path: |
          dialogue.pdf
          dialogue.icml
